# Generated by Django 4.2.5 on 2023-09-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderproduct',
            table='myapp_orderproduct',
        ),
    ]
