# Generated by Django 4.2.5 on 2023-09-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_orderproduct_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderproduct',
            table=None,
        ),
    ]
