# Generated by Django 4.2.5 on 2023-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_orderproduct_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/Users/Dolzh/OneDrive/Рабочий стол/таврели/2.jpg', upload_to='product_photos/'),
            preserve_default=False,
        ),
    ]
